name: Update and Deploy Docker

on:
  push:
    branches:
      - main

jobs:
  update-and-run:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Run SSH command to update files and run script
      uses: appleboy/ssh-action@v0.1.3
      with:
        host: 85.132.120.12
        port: 22
        username: gitaction
        password: '@9BsFZ6La#hsVczx'
        script: |
          cd /root
          echo 'hello' > text.txt
