name: Update and Deploy Docker

on:
  push:
    branches:
      - main

jobs:
  update-and-run:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Run SSH command to update files and run script
      uses: appleboy/ssh-action@v0.1.3
      with:
        host: ${{ secrets.SSH_IP }}
        port: 22
        username: ${{ secrets.SSH_USERNAME }}
        password: ${{ secrets.SSH_PASSWORD }}
        script: |
          cd /root
          echo 'hello' > text.txt
