name: Update and Deploy Docker

on:
  push:
    branches:
      - main

jobs:
  update-and-run:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Run SSH command to update files and run script
      uses: appleboy/ssh-action@v0.1.3
      with:
        host: ${{ secrets.SSH_IP }}
        port: 2222
        username: ${{ secrets.SSH_USERNAME }}
        password: ${{ secrets.SSH_PASSWORD }}
        #script: |
          cd /opt/salesBackendAPK/
          docker compose down
          mv app.log /home/gitaction/app.log.$(date +%F-%H-%M)
          rm -rf *
          docker image rm salesbackendapk-app
          cd ~/
          git clone git@github.com:MuradAbbaszade/pashapay-volunteer.git
          cd /opt/salesBackendAPK/
          mv ~/pashapay-volunteer/* /opt/salesBackendAPK/
          docker compose up -d
